# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - group: "Unit Tests on TPU"
    depends_on: "build_docker"
    steps:
      - label: "Unit Tests (PR)"
        key: "unit_tests_pr"
        if: 'build.env("NIGHTLY") != "1"'
        agents:
          queue: "tpu_v7x_8_queue"
        env:
          MODEL_IMPL_TYPE: "vllm"
        commands:
          - "bash .buildkite/scripts/run_in_docker.sh bash ./scripts/vllm/benchmarking/run_unit_test.sh no"

      - label: "Unit Tests (Nightly)"
        key: "unit_tests_nightly"
        if: 'build.env("NIGHTLY") == "1"'
        agents:
          queue: "tpu_v7x_8_queue"
        env:
          MODEL_IMPL_TYPE: "vllm"
        commands:
          - "bash .buildkite/scripts/run_in_docker.sh bash ./scripts/vllm/benchmarking/run_unit_test.sh yes"
