#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Fail when a kernel file gains a closure that captures a loop variable.

Ruff's B023 is selected for the whole tree except ``src/vllm_torchtpu/kernels``,
where ``pl.when`` and ``pl.loop`` call the decorated body immediately and the
rule has no way to tell that apart from a closure that escapes its loop. Every
finding there today is one of those, so the rule is turned off for that
directory in pyproject.toml.

That exemption on its own would let real captures in later unnoticed. This is
a ratchet: ``tools/b023_baseline.txt`` records how many findings each kernel
file has today, a file that gains one fails the hook, and a file that loses
one fails until the baseline is shrunk. The count can only go down.

A count says a file gained a finding, not which closure is new. Run ruff
directly to see the sites:

    ruff check --select B023 --config 'lint.per-file-ignores={}' \\
        src/vllm_torchtpu/kernels

Run directly to see the current state:

    tools/check_b023_baseline.py            # check
    tools/check_b023_baseline.py --update   # rewrite the baseline
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
BASELINE_PATH = REPO_ROOT / "tools" / "b023_baseline.txt"

# The directory B023 is switched off for. Mirrors the per-file-ignores entry
# in pyproject.toml; the two move together.
KERNELS = "src/vllm_torchtpu/kernels"


def count_findings() -> dict[str, int]:
    """B023 findings per file, keyed by repo-relative path.

    `per-file-ignores` is emptied so the kernel exemption does not hide the
    findings this is counting. Only B023 is selected, so dropping the other
    per-file entries cannot matter.
    """
    result = subprocess.run(
        [
            "ruff",
            "check",
            "--no-cache",
            "--select",
            "B023",
            "--config",
            "lint.per-file-ignores={}",
            "--output-format",
            "json",
            KERNELS,
        ],
        cwd=REPO_ROOT,
        stdout=subprocess.PIPE,
        text=True,
        check=False,
    )
    # ruff exits 1 when it reports findings, which is the normal case here.
    # Any other code means it could not run, and the output is not JSON.
    if result.returncode not in (0, 1):
        raise RuntimeError(f"ruff exited {result.returncode}:\n{result.stdout}")

    counts: collections.Counter[str] = collections.Counter()
    for finding in json.loads(result.stdout):
        path = pathlib.Path(finding["filename"])
        counts[path.relative_to(REPO_ROOT).as_posix()] += 1
    return dict(counts)


def load_baseline() -> dict[str, int]:
    counts = {}
    for line in BASELINE_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        path, _, count = line.rpartition(":")
        counts[path.strip()] = int(count)
    return counts


def write_baseline(counts: dict[str, int]) -> None:
    header = (
        "# B023 findings per kernel file, as of the last update.\n"
        "# Generated by tools/check_b023_baseline.py --update.\n"
        "# Shrink this file by binding the loop variable; never grow it.\n"
    )
    body = "".join(f"{path}: {counts[path]}\n" for path in sorted(counts))
    BASELINE_PATH.write_text(header + body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the baseline from the current tree",
    )
    # pre-commit passes the staged filenames; this hook always scans the
    # whole kernels directory, so accept and ignore them.
    parser.add_argument("filenames", nargs="*", help=argparse.SUPPRESS)
    args = parser.parse_args()

    found = count_findings()
    if args.update:
        write_baseline(found)
        print(f"baseline updated: {sum(found.values())} findings in {len(found)} files")
        return 0

    baseline = load_baseline()
    grew = sorted(path for path, n in found.items() if n > baseline.get(path, 0))
    shrank = sorted(path for path, n in baseline.items() if found.get(path, 0) < n)

    if grew:
        print("These kernel files gained a closure over a loop variable:\n")
        for path in grew:
            print(f"  {path}  {baseline.get(path, 0)} -> {found[path]}")
        print(
            "\nBind the variable at definition time, by passing it as a "
            "keyword-only default, so the closure does not read it later:\n"
            "    def body(*, rows=rows):\n"
            "A `pl.when` or `pl.loop` body runs inside the iteration that "
            "defined it and is safe as written; if that is what this is, "
            "run `tools/check_b023_baseline.py --update` and say so in the "
            "review."
        )
        return 1

    if shrank:
        print("These kernel files have fewer findings than the baseline (nice):\n")
        for path in shrank:
            print(f"  {path}  {baseline[path]} -> {found.get(path, 0)}")
        print(
            "\nRun `tools/check_b023_baseline.py --update` to shrink the "
            "baseline, and commit it."
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
