# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI - Presubmit on TPU

on:
  # Enable remote connections.
  # Step 1: Add a workflow dispatch to enable halting.
  # See go/ml-github-actions:connect#enable-workflow-dispatch.
  workflow_dispatch:
    inputs:
      halt-for-connection:
        description: 'Should this workflow run wait for a remote connection?'
        type: choice
        default: 'no'
        options:
          - 'yes'
          - 'no'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  issues: read

# Cancel old jobs when they are replaced by new runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # Don't cancel in-progress jobs for main branch
  cancel-in-progress: ${{ github.ref != 'main' }}

jobs:
  run_tests:
    # Disable on forks
    if: github.event.repository.fork == false

    defaults:
      run:
        shell: bash

    name: "Presubmit on ${{ matrix.job_info.runner }}"
    # Available self-hosted runners: b/455965440#comment6
    strategy:
      matrix:
        job_info: [
          {
            runner: "linux-x86-tpu7x-224-4tpu",
            container: "us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest",
          }
        ]
        python-version: [3.12]
    # Use self-hosted runners. For a Linux runner, a corresponding container image used for the
    # workflow is required.
    # See go/ml-github-actions/getting_started/using_runners.md#supported-runner-scale-set.
    runs-on: ${{ matrix.job_info.runner }}
    container:
      image: ${{ matrix.job_info.container }}

    env:
      # Enable color in logs
      FORCE_COLOR: "1"

    steps:
      # Clone the GitHub repository to runner's environment $GITHUB_WORKSPACE, making its files
      # accessible for workflow to use. Otherwise, the workflow cannot find the files (e.g. ls -lR
      # will return "total 0").
      # Pin to to a SHA for security, see https://opensource.google/documentation/reference/github/services#actions
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Mark git directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Virtual Environment
        run: |
          # Set up python virtual environment
          uv venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> "$GITHUB_ENV"
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"

          # UV uses these to auth into the torch-tpu index defined in pyproject.toml
          echo UV_INDEX_TORCH_TPU_REGISTRY_USERNAME="oauth2accesstoken" >> "$GITHUB_ENV"
          echo UV_INDEX_TORCH_TPU_REGISTRY_PASSWORD="$(gcloud auth print-access-token)" >> "$GITHUB_ENV"

      - name: Install Dependencies
        run: uv sync --extra test --prerelease allow

      # Enable remote connections.
      # See go/ml-github-actions:connect#add-waiting-step.
      - name: Wait For Connection
        uses: google-ml-infra/actions/ci_connection@9f8d7d8d9954430d0fef4a8cce2cb4e3844c200d
        with:
          halt-dispatch-input: ${{ inputs.halt-for-connection }}

      - name: Run tests
        run: |
          # Print installed packages
          echo "Installed packages:"
          uv pip freeze

          export MODEL_IMPL_TYPE="vllm"

          # Run tests from a temp dir to force Python to test the installed package, not local source files.
          # see https://blog.ganssle.io/articles/2019/08/test-as-installed.html
          TEST_DIR="$PWD/tests"
          cd "$(mktemp -d)"
          pytest "$TEST_DIR"  -sv --timeout=300
